### ISSUE TITLE
Panic in `pulldown_latex::push_mathml`

### ISSUE THREAD

**Issue by rfuzz** [carloskiki/pulldown-latex#19]
Hello, while performing fuzz testing, I encountered an input that causes the `pulldown_latex::push_mathml` function to panic:

```rust
use pulldown_latex::{Parser, Storage, push_mathml};

fn main() {
    let s = r#"{%"#;
    let storage = Storage::new();
    let parser = Parser::new(s, &storage);
    let mut mathml = String::new();
    let config = Default::default();

    match push_mathml(&mut mathml, parser, config) {
        Ok(()) => println!("{}", mathml),
        Err(e) => eprintln!("Error while rendering: {}", e),
    }
}
```

Upon running the code, the following panic occurs:

```shell
thread 'main' panicked at /home/ubuntu/pulldown-latex/src/parser/lex.rs:72:41:
range start index 2 out of range for slice of length 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:74:14
   2: core::slice::index::slice_start_index_len_fail_rt
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/slice/index.rs:43:5
   3: core::slice::index::slice_start_index_len_fail
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/slice/index.rs:37:5
   4: <core::ops::range::RangeFrom<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/slice/index.rs:589:13
   5: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/slice/index.rs:16:9
   6: pulldown_latex::parser::lex::group_content
             at /home/ubuntu/pulldown-latex/src/parser/lex.rs:72:41
   7: pulldown_latex::parser::primitives::<impl pulldown_latex::parser::InnerParser>::handle_char_token
             at /home/ubuntu/pulldown-latex/src/parser/primitives.rs:71:29
   8: pulldown_latex::parser::InnerParser::parse
             at /home/ubuntu/pulldown-latex/src/parser.rs:248:36
   9: pulldown_latex::parser::InnerParser::parse_next
             at /home/ubuntu/pulldown-latex/src/parser.rs:351:10
  10: <pulldown_latex::parser::Parser as core::iter::traits::iterator::Iterator>::next
             at /home/ubuntu/pulldown-latex/src/parser.rs:121:36
  11: <pulldown_latex::mathml::ManyPeek<I> as core::iter::traits::iterator::Iterator>::next::{{closure}}
             at /home/ubuntu/pulldown-latex/src/mathml.rs:1166:44
  12: core::option::Option<T>::or_else
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/option.rs:1542:21
  13: <pulldown_latex::mathml::ManyPeek<I> as core::iter::traits::iterator::Iterator>::next
             at /home/ubuntu/pulldown-latex/src/mathml.rs:1166:9
  14: pulldown_latex::mathml::MathmlWriter<I,W>::write
             at /home/ubuntu/pulldown-latex/src/mathml.rs:828:33
  15: pulldown_latex::mathml::push_mathml
             at /home/ubuntu/pulldown-latex/src/mathml.rs:1339:5
  16: pulldown_latex_fuzz_target_test::main
             at ./src/main.rs:10:11
  17: core::ops::function::FnOnce::call_once
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

version: `commit a94f7777cff8470425fa950c26cf4f852fc3929c`

**Comment by carloskiki** [comment]
Noted! will look into it.

**Comment by carloskiki** [comment]
I have fixed it in my current branch of the project where I have breaking changes. Hopefully I will be able to merge it by the end of the week and release 0.7.

Thank you! If you ever want to implement a fuzzer for latex math, I'd love to help you and it would benefit the project greatly :)

**Comment by rfuzz** [comment]
Thank you for your kind offer! I may further explore fuzz testing the LaTeX parser, and I hope my work will benefit the project.

**Comment by carloskiki** [comment]
Closing as v0.7 is now released
